name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li6CkI6nazWOp9bP"
GITHUB_OWNER = "qiuday"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-74u.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-74u.pages.dev/"

